# Generated by Django 2.2.2 on 2019-07-01 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_desc', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50)),
                ('ilo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('server_desc', models.CharField(max_length=200)),
                ('server_type', models.CharField(max_length=50)),
                ('server_vendor', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('product', models.ManyToManyField(to='env_page.Product')),
                ('project', models.ManyToManyField(to='env_page.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_desc', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env_page.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=50)),
                ('network_desc', models.CharField(max_length=200)),
                ('vlan', models.CharField(max_length=50)),
                ('bond', models.CharField(max_length=50)),
                ('ethnet', models.CharField(max_length=50)),
                ('bridge_name', models.CharField(max_length=50)),
                ('ipv4', models.GenericIPAddressField()),
                ('ipv4_prefix', models.IntegerField()),
                ('ipv4_gw', models.GenericIPAddressField()),
                ('ipv6', models.GenericIPAddressField()),
                ('ipv6_prefix', models.IntegerField()),
                ('ipv6_gw', models.GenericIPAddressField()),
                ('create_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env_page.Server')),
            ],
        ),
    ]
